#!/bin/ash
sudo su

# https://wiki.postmarketos.org/index.php?title=Telegram_Desktop&mobileaction=toggle_view_mobile
apk add telegram-desktop
telegram-desktop -scale 80
echo "#!/bin/ash" >> ~/.local/bin/telegram-desktop-wayland
echo "QT_QPA_PLATFORM=wayland telegram-desktop" >> ~/.local/bin/telegram-desktop-wayland
chmod +x ~/.local/bin/telegram-desktop-wayland
cp /usr/share/applications/telegram-desktop.desktop ~/.local/share/applications/
gedit ~/.local/share/applications/telegram-desktop.desktop
# Exec=telegram-desktop -scale 80 -- %u
apk add gnome-weather

apk add flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub io.freetubeapp.FreeTube

flatpak install --user https://dl.flathub.org/repo/appstream/org.opencpn.OpenCPN.flatpakref

