#!/usr/bin/env bash

## CREDENTIALS

# NGINX
export MYSQL_ROOT_PASSWORD=$(secret-tool lookup Title mysql-root-password)
export MYSQL_PASSWORD=$(secret-tool lookup Title mysql-password)

# DUCKDNS
DUCKDNS_TOKEN=1fdfce71-c2b1-4a01-8f9f-250665e36133


access_key_id=$(secret-tool lookup Title aws-access-key-id)
secret_access_key=$(secret-tool lookup Title aws-secret-access-key)

printf "{
  \"Version\": 1,
  \"AccessKeyId\": \"%s\",
  \"SecretAccessKey\": \"%s\"
}" "$access_key_id" "$secret_access_key"
